// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.31.0--rc1
// source: proto/pvz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pvz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{0}
}

type PVZ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	City         string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	RegisteredAt string `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pvz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *PVZ) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PVZ) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PVZ) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type PVZList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pvzs []*PVZ `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
}

func (x *PVZList) Reset() {
	*x = PVZList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pvz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVZList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZList) ProtoMessage() {}

func (x *PVZList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZList.ProtoReflect.Descriptor instead.
func (*PVZList) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *PVZList) GetPvzs() []*PVZ {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

var File_proto_pvz_proto protoreflect.FileDescriptor

var file_proto_pvz_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x76, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x4e, 0x0a, 0x03, 0x50, 0x56, 0x5a, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x29, 0x0a, 0x07, 0x50, 0x56, 0x5a, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04,
	0x70, 0x76, 0x7a, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x56, 0x5a, 0x52, 0x04, 0x70, 0x76, 0x7a, 0x73, 0x32, 0x37, 0x0a, 0x0a,
	0x50, 0x56, 0x5a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x56, 0x5a, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x56, 0x5a, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x69, 0x6e, 0x6d, 0x61, 0x72, 0x6b, 0x2f, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x65, 0x2d, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x67, 0x2d,
	0x32, 0x30, 0x32, 0x35, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pvz_proto_rawDescOnce sync.Once
	file_proto_pvz_proto_rawDescData = file_proto_pvz_proto_rawDesc
)

func file_proto_pvz_proto_rawDescGZIP() []byte {
	file_proto_pvz_proto_rawDescOnce.Do(func() {
		file_proto_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pvz_proto_rawDescData)
	})
	return file_proto_pvz_proto_rawDescData
}

var file_proto_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_pvz_proto_goTypes = []interface{}{
	(*Empty)(nil),   // 0: proto.Empty
	(*PVZ)(nil),     // 1: proto.PVZ
	(*PVZList)(nil), // 2: proto.PVZList
}
var file_proto_pvz_proto_depIdxs = []int32{
	1, // 0: proto.PVZList.pvzs:type_name -> proto.PVZ
	0, // 1: proto.PVZService.ListPVZ:input_type -> proto.Empty
	2, // 2: proto.PVZService.ListPVZ:output_type -> proto.PVZList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pvz_proto_init() }
func file_proto_pvz_proto_init() {
	if File_proto_pvz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pvz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pvz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVZ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pvz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVZList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pvz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pvz_proto_goTypes,
		DependencyIndexes: file_proto_pvz_proto_depIdxs,
		MessageInfos:      file_proto_pvz_proto_msgTypes,
	}.Build()
	File_proto_pvz_proto = out.File
	file_proto_pvz_proto_rawDesc = nil
	file_proto_pvz_proto_goTypes = nil
	file_proto_pvz_proto_depIdxs = nil
}
