version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pvz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      DB_URL: postgres://user:pass@db:5432/pvz?sslmode=disable
      JWT_SECRET: secret
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9000:9000"